name: Check AWS Access

on:
  push :
    branches:
      - main
permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  check-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::559050225197:role/actions-role
        role-session-name: githubactions-role
        aws-region: "us-east-1"
    - name: Verify AWS credentials
      run: aws sts get-caller-identity
